# Generated by Django 5.0.2 on 2024-02-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0002_alter_comment_article_alter_replay_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at', 'comment']},
        ),
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-created_at', '-updated_at', 'replay'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='replay',
            old_name='content',
            new_name='replay',
        ),
    ]
