# Generated by Django 5.0.2 on 2024-02-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0003_alter_comment_options_alter_replay_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
