# Generated by Django 5.0.2 on 2024-02-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0004_alter_comment_options_rename_comment_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.RenameField(
            model_name='replay',
            old_name='replay',
            new_name='content',
        ),
    ]
