# Generated by Django 5.0.2 on 2024-02-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0005_alter_replay_options_rename_replay_replay_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='content',
            new_name='replay',
        ),
    ]
