# Generated by Django 5.0.2 on 2024-02-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0006_rename_content_replay_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='App_Teacher.article'),
        ),
    ]
