# Generated by Django 5.0.2 on 2024-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0011_alter_quiz_answer_answerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlist',
            name='answer',
            field=models.CharField(choices=[('', 'Select Correct Answer'), ('option_1', '(A)'), ('option_2', '(A)'), ('option_3', '(A)'), ('option_4', '(A)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(choices=[('', 'Select Correct Answer'), ('option_1', '(A)'), ('option_2', '(A)'), ('option_3', '(A)'), ('option_4', '(A)')], max_length=15),
        ),
    ]
