# Generated by Django 5.0.2 on 2024-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Teacher', '0012_alter_answerlist_answer_alter_quiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlist',
            name='answer',
            field=models.CharField(choices=[('', 'Select Correct Answer'), ('option_1', '(A)'), ('option_2', '(B)'), ('option_3', '(C)'), ('option_4', '(D)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(choices=[('', 'Select Correct Answer'), ('option_1', '(A)'), ('option_2', '(B)'), ('option_3', '(C)'), ('option_4', '(D)')], max_length=15),
        ),
    ]
